import Head from 'next/head'
import HomeScreen from './Home/HomeScreen'
import Login from '../pages/validation/Login'

export default function Home() {
  return (
    <>
      <Head>
        <title>Minor Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      <HomeScreen/>
      {/* <Login/> */}
      </main>
    </>
  )
}
